### ISSUE TITLE
Way to change sendname

### ISSUE THREAD

**Issue by daurnimator** [wahern/cqueues#137]
Currently you have to provide the TLS SNI host to `cqueues.socket.connect`, there is no way to change it afterwards.

I'm surprised you can't pass it as part of the context to `:starttls`

Possibly related to #74 (if fix is to add a general `:setoptions` method)

**Comment by wahern** [comment]
On Mon, Feb 29, 2016 at 04:20:21AM -0800, daurnimator wrote:
> Currently you have to provide the TLS SNI host to `cqueues.socket.connect`, there is no way to change it afterwards.
> 
> I'm surprised you can't pass it as part of the context to `:starttls`
> 
> Possibly related to #74 (if fix is to add a general `:setoptions` method)

The underlying headache is that lib/socket.c was originally written for C
programs. The idea was that you create a socket, and then you can
immediately begin reading and writing, without having to handle DNS,
connect, starttls, etc, separately. In the context of C and asynchronous
I/O, waiting for those things explicitly in C means additional states and
callbacks for event processing, and that kind of complexity is really risky
in C.

The Lua module socket API tracked the C library API too closely. There's
little benefit from Lua provided by the C library semantics because event
management is already transparent. And people expect the regular BSD sockets
API, for better or worse.

So I think we maybe need to step back and figure out how to refactor
lib/socket.c to make it easier to expose more low-level details to Lua code.
But keep in mind that lib/socket.c is still heavily used in several other C
applications, and I'd hate to see it forked because wider usage helps
uncover bugs more quickly.

**Comment by daurnimator** [comment]
> The underlying headache is that lib/socket.c was originally written for C programs. The idea was that you create a socket, and then you can immediately begin reading and writing, without having to handle DNS, connect, starttls, etc, separately. In the context of C and asynchronous I/O, waiting for those things explicitly in C means additional states and callbacks for event processing, and that kind of complexity is really risky in C.
> 
> The Lua module socket API tracked the C library API too closely. There's little benefit from Lua provided by the C library semantics because event management is already transparent. And people expect the regular BSD sockets API, for better or worse.

I like it :)
It lets you kick off things knowing they'll be completed in future (without having to create another thread a condition to wait on).
+ the model works well with features I'd like to add (like TCP Fast Open #52)

> keep in mind that lib/socket.c is still heavily used in several other C
applications, and I'd hate to see it forked because wider usage helps
uncover bugs more quickly.

It would be nice to keep socket.c as a separate project IMO. Possibly bring it in via a git subtree (same with dns.c). I know we touched on this when I was in SF.

---------------------------

To solve this issue I see two possible solutions:
  - Allow the sendname to be passed as part of `SSL_CTX` if given?(I guess this means binding `SSL_CTX_set_tlsext_servername_callback` in luaossl?)
  - Add `cqueues.socket:setoptions`
    This would also solve some other issues (such as #74).
    Things such as `so_cloexec` and `so_nopush` could just be a wrapper around `setoptions`

**Comment by daurnimator** [comment]
Solution available via 0cf477bc05ce7c11cb6c2e8dea81a643d3c70482
