### ISSUE TITLE
Why preserve ETIMEDOUT?

### ISSUE THREAD

**Issue by daurnimator** [wahern/cqueues#143]
Why is ETIMEDOUT preserved across socket operations?

It seems like the operation that retries are *most* likely to proceed further with.

**Comment by wahern** [comment]
Originally cqueues threw most errors, but not ETIMEDOUT; and didn't preserve errors at all. That decision was based on the logic that a common error like ETIMEDOUT is often recoverable (and maybe not even an error at all), whereas most other errors are not recoverable and so should be thrown by default. And that smart applications would use conditional logic at all the appropriate places to catch errors.

But that didn't work out well in practice. First, because throwing is often unexpected and confusing, and often requires coding contrivances when you decide to handle a specific error. Second, because I found several application bugs which were ignoring inline errors (specifically ETIMEDOUT, the only one not thrown), and ultimately ending up in tight loop (e.g. because of a bug in calculating the timeout). They weren't outright ignoring them entirely, but were performing some I/O operations unconditionally.

That's when I saw the wisdom in C stdio's ferror, feof, and clearerr. Preserving errors and requiring an explicit clearerr means that it's really difficult for errors to be accidentally dropped on the floor and a program to proceed in blissful ignorance, while at the same time not requiring application code to deal with exceptions if they don't want. But like exceptions, you can perform several I/O operations unconditionally, only checking at the very end of the block whether they all succeeded:

```
for _,data in ipairs(buffer) do
  con:write(data)
end
con:write(trailer)
assert(con:flush())
```

It also has the benefit of breaking less code when the semantics are fully switched over to not throwing errors.

Preserving ETIMEDOUT might make some cases more burdensome to implement, but I think it's the safest behavior overall, and an acceptable trade-off. If checking for errors on each, individual operation seems mentally burdensome, then error preservation is exactly what you want to save you from yourself.

**Comment by daurnimator** [comment]
btw, I was thinking about how EAGAIN is currently coerced to ETIMEDOUT.
This makes it impossible to differentiate a ETIMEDOUT from the OS vs an ETIMEDOUT injected by cqueues.
Perhaps we should just return EAGAIN when the cqueues deadline is elapsed?

**Comment by daurnimator** [comment]
The issue I'm having with the `ferror`/`clearerr` like scheme is that it makes things hard to wrap at a higher level. For any moderately complex object that uses a cqueues socket underneath, I need to call `clearerr` after most operations; and then (optionally) reimplement my own `:seterror()`/`:clearerr()` and check for errors at the start of each method.

I guess the answer is to use `sock:recv()` directly (as the `:seterror` is done from the `:read` and `:xread` wrappers).

**Comment by wahern** [comment]
Can you give an example? I'm not getting why you would always want to clear an error, rather than bubble it back up to the caller.

Regarding EAGAIN vs ETIMEDOUT, that's an interesting idea. I don't think it's possible to get ETIMEDOUT on reading a non-blocking socket. But on a write, maybe (because TCP stack couldn't flush the kernel buffer), and I assume its definitely possible on a non-blocking connect. I'll create a ticket.

**Comment by daurnimator** [comment]
> Can you give an example? I'm not getting why you would always want to clear an error, rather than bubble it back up to the caller.

e.g. in lua-http, there is a function `h1_connection:get_next_incoming_stream(timeout)`. It returns the next stream on the connection. It blocks until at least one byte is available in an unclaimed stream (it waits for a lock on reading, then uses `socket:fill()`) so that you don't just get infinite streams with the loop `while true do local stream = h1_connection:get_next_incoming_stream(); cq:wrap(handle_stream, stream) end`.
Now.... waiting for the read lock doesn't set the error state. However waiting for `socket:fill()` does.
Either I should emulate cqueues and have my own `:seterror` and `:clearerr` for when you don't obtain the lock in time; or I need to call `:clearerr` after a failure.

**Comment by wahern** [comment]
On Thu, May 26, 2016 at 02:56:28AM -0700, daurnimator wrote:
> > Can you give an example? I'm not getting why you would always want to clear an error, rather than bubble it back up to the caller.
> 
> e.g. in lua-http, there is a function `h1_connection:get_next_incoming_stream(timeout)`. It returns the next stream on the connection. It blocks until at least one byte is available in an unclaimed stream (it waits for a lock on reading, then uses `socket:fill()`) so that you don't just get infinite streams with the loop `while true do local stream = h1_connection:get_next_incoming_stream(); cq:wrap(handle_stream, stream) end`.
> Now.... waiting for the read lock doesn't set the error state. However waiting for `socket:fill()` does.
> Either I should emulate cqueues and have my own `:seterror` and `:clearerr` for when you don't obtain the lock in time; or I need to call `:clearerr` after a failure.
> 

IOW, easily resolvable in lua-http? ;)

**Comment by daurnimator** [comment]
> IOW, easily resolvable in lua-http? ;)

Yeah. I ended up just adding my own `onerror` function that calls `:clearerr` on ETIMEDOUT. https://github.com/daurnimator/lua-http/blob/4c20421bcceb2e2bc232017ac5215f16362f18a2/http/h1_connection.lua#L24
