### ISSUE TITLE
Problem with DNS query

### ISSUE THREAD

**Issue by torhve** [wahern/cqueues#153]
Running a few DNS queries in a loop on LuaJIT results in:

`/usr/local/share/lua/5.1/cqueues/dns/resolvers.lua:78: table index is nil`

My code that triggers this is just a `dns.query(host, 'AAAA', 'IN', 5)`

I was unable to build a minimal test case, so I'm not sure what's going on entirely

**Comment by daurnimator** [comment]
Trying to guess the traceback:
  - https://github.com/wahern/cqueues/blob/master/src/dns.resolvers.lua#L78
  - https://github.com/wahern/cqueues/blob/master/src/dns.resolvers.lua#L129
  - Which can only be reached with `res == nil` if neither of the preceding `if` branches are taken. i.e. `cache_len == 0` and `self.alive.n > self.hiwat`.

My diagnosis is this case is actually intentional; and that `alive:add` should only be called if `tryget` is successful.

**Comment by torhve** [comment]
Minimal code to reproduce 
```
#!/usr/bin/env luajit                             
cqueues = require 'cqueues'                       
dns = require'cqueues.dns'                        
                                                  
host = 'google.com'                               
q = cqueues.new()                                 
q:wrap(function()                                 
  for i=1,33 do                                   
    answer = dns.query(host, 'AAAA', 'IN', 1)     
  end                                             
end)                                              
assert(q:loop())                                  

```
