### ISSUE TITLE
What to do on "internal error in continuation queue: Bad file descriptor"

### ISSUE THREAD

**Issue by daurnimator** [wahern/cqueues#53]
One of my servers threw at the top level with "internal error in continuation queue: Bad file descriptor"
What does this mean? How can I debug/fix it?

I see two places this could be thrown from:
  - https://github.com/wahern/cqueues/blob/56fd893388f592fa2e8f9cb91b99231b1ba8a23e/src/cqueues.c#L1620
  - https://github.com/wahern/cqueues/blob/56fd893388f592fa2e8f9cb91b99231b1ba8a23e/src/cqueues.c#L1670

**Comment by wahern** [comment]
See section 3.1.3 in the manual. EBADF usually happens when code tries to poll on an invalid descriptor, or when a descriptor is closed before removing it from the event queue.

Sometimes it's benign, like when a module closes a descriptor behind your back. Other times it's symptomatic of a race condition, uninitialized data, or memory corruption.

**Comment by daurnimator** [comment]
> See section 3.1.3 in the manual. EBADF usually happens when code tries to poll on an invalid descriptor, or when a descriptor is closed before removing it from the event queue.

In this particular circumstance I was using [cqueues-pgsql](https://github.com/daurnimator/cqueues-pgsql). I don't have any code that closes the fd being used (it's open for the life of the program). So unless I'm missing a case where it is closed inside of libpq, then I'm afraid it could be the last option from the manual:
> With Lua code using the cqueues APIs, EBADF should never
be encountered. When it does occur, it’s a sure sign of a bug somewhere in the parent application
or an extension module and—hopefully—not cqueues.

------------------------------

I've also seen "internal error in continuation queue: Operation not permitted". Any words of wisdom about what might cause that?

**Comment by wahern** [comment]
On Thu, Feb 19, 2015 at 07:32:23AM -0800, daurnimator wrote:
> > See section 3.1.3 in the manual. EBADF usually happens when code tries to poll on an invalid descriptor, or when a descriptor is closed before removing it from the event queue.
> 
> In this particular circumstance I was using [cqueues-pgsql](https://github.com/daurnimator/cqueues-pgsql). I don't have any code that closes the fd being used (it's open for the life of the program). So unless I'm missing a case where it is closed inside of libpq, then I'm afraid it could be the last option from the manual:
> > With Lua code using the cqueues APIs, EBADF should never
> be encountered. When it does occur, it???s a sure sign of a bug somewhere in the parent application
> or an extension module and???hopefully???not cqueues.
> 

Looking at the libpq code things should be fine as long as you don't call
PQreset or similar.

More likely is that the object is being closed (explicitly or via garbage
collection) while the descriptor is still in the event queue. I don't see
anywhere in cqueues-psql.lua a call to cqueues.cancel. 

When a call to cqueues.poll returns, the descriptor is still in the event
queue. cqueues.poll doesn't add and delete the descriptor each time it's
called. Under load that would give performance roughly on par with select or
poll.

What cqueues.poll does is wait until you poll again. If you're polling on
the same descriptor, it leaves the descriptor installed. If the descriptor
is different, it removes the old descriptor and installs the new one.
Basically, cqueues only modifies the set of installed events when the
application transitions to polling on a different descriptor, different
events, or the thread exits. But the old descriptor has to remain valid
until this happens. Normally this just works. It fails if the descriptor is
closed before cqueues is explicitly (cqueues.cancel) or implicitly (another
yield/resume cycle) notified of the transition.

All the internal modules call cqs_cancelfd before any descriptor is closed.
Other modules need to call cqueues.cancel.

Some libraries like libevent ignore EBADF when deleting an event. But this
hides bugs. Imagine worker A polls on fd 3, performs a read, then closes fd
3. Before the loop finishes and the set of events are updated, worker B
opens a new socket. Because POSIX requires the lowest descriptor number to
be returned, it's likely that the new socket will be fd 3. Worker B
immediately attempts a read and then polls.

The problem is that close(2) will automatically delete a descriptor from an
epoll or kqueue set. However, the event library can't know that. It still
has fd 3 marked as being installed. So when worker B polls, the event
library believes it's already installed. Worker B ends up stalling. Then
maybe it hits its timeout and performs the read. Everything seems to be
working; you might just think the network is crappy.

Basically, in both cqueues, libevent, or direct use of epoll or kqueue, you
have to make sure that you delete any persistent events before closing a
descriptor. It's just not as obvious in cqueues because the management of
persistent events is mostly transparent, especially when using the built-in
modules.

FWIW, cqueues.cancel won't throw an error on EBADF. I throw EBADF inside the
event loop controller simply because it's a complex and risky proposition to
try to recover from that kind of an error, which is always technically
symptomatic of a bug, either in cqueues or the application. There's some
unused and untested code to try to reset an event queue, but I've kind of
soured on the idea. Another idea is to resume any threads polling on the bad
descriptor and either return or throw an error. At least then it might be
easier to track down the source of the problem.

**Comment by daurnimator** [comment]
> Other modules need to call cqueues.cancel.

Sigh, okay. I'll add this to cqueues-pgsql now.

**Comment by daurnimator** [comment]
so today I got `EBADF` again... (with that new cqueues-pgsql commit that uses `cqueues.cancel`)

**Comment by wahern** [comment]
Did you ever figure this out?

**Comment by daurnimator** [comment]
> Did you ever figure this out?

No :( I had to take the code out of production as I ran out of time to debug.

**Comment by daurnimator** [comment]
I think I figured this out. Hopefully fixed with https://github.com/daurnimator/cqueues-pgsql/pull/3/commits/7bed63cfeec6734873ac6ec5c52b608a2df52ce3
