### ISSUE TITLE
Is it safe to call cqueues.cancel(-1)?

### ISSUE THREAD

**Issue by daurnimator** [wahern/cqueues#54]
Is it safe to call `cqueues.cancel(-1)`?
Please consider documenting this; and even special casing it in the code.

**Comment by daurnimator** [comment]
I can see in the [code](https://github.com/wahern/cqueues/blob/master/src/cqueues.c#L2033) that `cqueue_cancel` via way of `cqueue_checkfd` will actually call `cqueue_cancelfd` with `fd = -1`

**Comment by wahern** [comment]
1) Any errors when canceling aren't bubbled up right now.

2) If and when that changes, -1 will always be harmless because if the descriptor is not currently polling it makes sense to return success. Like free(NULL)** there's no benefit to failing those cases. Requiring an application to only cancel installed descriptors would be all burden and no benefit.

** -1 is like the NULL of descriptor numbers.

**Comment by daurnimator** [comment]
> 2) If and when that changes, -1 will always be harmless because if the descriptor is not currently polling it makes sense to return success. Like free(NULL)** there's no benefit to failing those cases. Requiring an application to only cancel installed descriptors would be all burden and no benefit.

Excellent. Could this be mentioned in the manual text?
