### ISSUE TITLE
socket:connect() erroring rather than returning error value on rejected connection

### ISSUE THREAD

**Issue by AlissaSquared** [wahern/cqueues#57]
If I use the following code:

```lua
local con = require( "cqueues.socket" ).connect( "random.bad.host", 7 )
con:connect( 1 )
```

I am given an error, when I'm told it's supposed to return an error value.
Is this expected behavior or is something wrong with cqueues?

**Comment by wahern** [comment]
See issue #16 and #8.

Unfortunately the default error handler throws anything that isn't EPIPE or ETIMEDOUT. [See `def_onerror` in src/socket.lua](https://github.com/wahern/cqueues/blob/c591c9d38d83bea1d4113988c3778cbfb260029b/src/socket.lua#L76).

Fortunately, until it's fixed, you can change the error handler globally using the socket.onerror prototype method or per-socket using the socket:onerror method. For example,

```lua
-- change error handler for all new sockets
socket.onerror(function (self, op, why, lvl)
    return why --> return errno directly to caller
end)
```

A somewhat related issue is #15. I want to create a flag day where all of this is fixed in one go, making the better behavior the default.

I originally threw uncommon errors because in practice I was encountering application code that would ignore errors. This sometimes caused difficult to track bugs, as well as causing some worker loops to spin and lock the process. But throwing is unhelpful for well-written code. In preparation for removing the default handler, I changed some behavior in the implementation. Now any error returned from the C binding will be saved and returned again for any subsequent send or receive operation (send and receive errors are handled separately). If the error is returned more than N times (where N is configurable using `socket:setmaxerrs` and defaults to 100), then the error is thrown. So if you handle an error you need to call `socket:clearerr`. This basically mirrors how stdio works in C.

**Comment by daurnimator** [comment]
Closing as duplicate.
