### ISSUE TITLE
writing from multiple threads needs locks

### ISSUE THREAD

**Issue by daurnimator** [wahern/cqueues#61]
Not entirely obvious is that if you want to write to a socket from multiple threads, you need to do your own locking.

Could we add a socket write buffering mode either succeeds or fails? (i.e. no half-writes, yielding, then writing more).

**Comment by wahern** [comment]
I think the better way to do this might be to put the socket into fully buffered mode and then set the output buffer to infinity. Then all writes will be copied to the output queue completely rather than only copying up to bufsiz bytes. You'll have to always explicitly :flush after writing. But this way multiple writers won't interleave.

However, currently :setbufsiz will reallocate the internal buffer. So socket:setbufsiz needs to be taught not to resize the buffer to infinity, leaving it to grow on demand. But that's a relatively easy fix--just fix lso_setbufsiz_ and lso_adjbufs to recognize special infinity values, which can be represented as (size_t)-1 internally.

The problem with internal socket locking (e.g. with cqueues condition variables) is that the :write wrappers would need to always first query the socket object to know whether to take a lock. So it slows down sockets for everybody.

**Comment by wahern** [comment]
Just committed support for infinite buffer sizes.

**Comment by daurnimator** [comment]
:+1:
