### ISSUE TITLE
:localname can return garbage memory

### ISSUE THREAD

**Issue by daurnimator** [wahern/cqueues#82]
The following will print `1`, a string containing a random 4 bytes of memory and `nil`
```lua
cs=require"cqueues.socket"
print(cs.pair():localname())
```

**Comment by daurnimator** [comment]
Notes:
  - this applies to `:peername` too
  - applies to unix sockets in general

Non-`.pair` example:
```lua
cs=require"cqueues.socket"
s=cs.listen{path="foo"}
c=cs.connect{path="foo"}
print(c:localname())
m=s:accept()
print(m:peername())
```

**Comment by daurnimator** [comment]
Code fix was in 5772df9, but docs need an update.
(under `:peername` they say: "For AF UNIX sockets, returns the address family and file path")

**Comment by wahern** [comment]
On Tue, Jul 28, 2015 at 10:15:30PM -0700, daurnimator wrote:
> Code fix was in 5772df9, but docs need an update.
> (under `:peername` they say: "For AF UNIX sockets, returns the address family and file path")
> 

Patches welcome :)

I did some testing and it turns out that getsockname on the listening and on
the accepted sockets will return the path name. getpeername on the
connecting socket will also return the path for BSD and Solaris, but not for
Linux or AIX.

Of course, for a socketpair there is no path to return. The bug was that for
an unnamed socket Linux would only fill in the .sun_family portion of the
address, and return a sockaddr length of 2. The rest was garbage from the
stack. Whereas everybody else (and Linux for named sockets even if the path
was empty) returned a sockaddr length of 16, which includes the first NUL
byte in sun_path.

Running some more tests I just noticed that on Solaris getpeername returns a
sockaddr length of 0 for unnamed Unix sockets. I should add all this to
PORTING.md.

**Comment by daurnimator** [comment]
A `nil` address breaks `logname` in socket.lua https://github.com/wahern/cqueues/blob/ff2cbd665715c3f56d5d8e2afcc4677af01f92a0/src/socket.lua#L55

**Comment by wahern** [comment]
Fixed logname.

**Comment by daurnimator** [comment]
The fix in 7b34b24c431ce02ee6d4a90b7fb5aa3f38b44456 isn't correct. it fails in the `if` statement trying to get the length (`#`) of `nil`.


The correct fix is something like:
```diff
-       elseif af == AF_UNIX and #addr > 0 then
-               return format("unix:%s", addr or "unnamed")
+       elseif af == AF_UNIX then
+               if addr and #addr > 0 then
+                       return format("unix:%s", addr)
+               else
+                       return "unix"
+               end
```

**Comment by wahern** [comment]
Oops. Thanks.

BTW, the reason I kept the colon was because "unix:" is common idiom (similar to a  URI scheme) that makes it easy to differentiate a hostname from a pathname, which may not be qualified with any directory separators.

**Comment by daurnimator** [comment]
> Oops. Thanks.

Fixed in a387351ef96e21d4e030dda93a99755afdaaa68f :)

**Comment by daurnimator** [comment]
(still needs docs in the tex/pdf)

**Comment by daurnimator** [comment]
This bug also manifests when using `SOCKET_DEBUG=1`:

```
$ SOCKET_DEBUG=1 lua -e 's,c=require"cqueues.socket".pair(); c:xwrite("hi", "n"); s:xread(2, 1)'
write([ð]:0): sent 2 bytes
  000000  68 69                                             |hi              |
read([]:0): rcvd 2 bytes
  000000  68 69                                             |hi              |
```
